trigger:
- none

variables:
- template: ./variables.yml

pool:
  vmImage: windows-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '$(serviceConnectionName)'
    scriptType: 'FilePath'
    scriptPath: '$(Build.SourcesDirectory)\pipeline-script.ps1'
    azurePowerShellVersion: 'LatestVersion'
    scriptArguments:
      -AssessedMachinesFilePath '$(Build.SourcesDirectory)\All_Assessed_Machines.csv' `
      -AssessedDisksFilePath '$(Build.SourcesDirectory)\All_Assessed_Disks.csv' `
      -RG '$(ResourceGroupName)' `
      -Location '$(location)' `
      -VNetName '$(virtualNetworkName)' `
      -SubnetName '$(subnetName)'